server:
  port: 8888
 
spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest    
  profiles:
    active: native
#    active: git

  cloud:
    config:
      server:
        git:
          uri: https://github.com/changwskr/spring-cloud-config
          force-pull: true          
        native:
          search-locations: file:///C:\WSJ_EX\01.workspace\2022-11-17-spring-cloud-config-native-repository
#          uri: file:///C:\WSJ_EX\01.workspace\2022-11-17-spring-cloud-config-native-repository 

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh

