server:
  port: 8888
spring:
  application:
    name: config-service
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
  profiles:
    active: native
#    active: git

  cloud:
    config:
      server:
        git:
          #uri: https://github.com/changwskr/spring-cloud-config
          uri: file:///C:\WSJ_EX\01.workspace\2022-11-17-spring-cloud-config-repository          
        native:
#          search-locations: C:\WSJ_EX\01.workspace\2022-11-17-spring-cloud-config-repository
          uri: file:///C:\WSJ_EX\01.workspace\2022-11-17-spring-cloud-config-repository     
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, beans, httptrace, busrefresh


