server:
  port: 8888


# --------------------------------------------------------------------
spring:
  application:
    name: config-service

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    
  profiles:
    active: native
#    active: git

  cloud:
    config:
      server:
        git:
          uri: file://C:\WSJ_EX\01.workspace\2022-11-17-spring-cloud-config-repository
#          uri: https://github.com/changwskr/spring-cloud-config
#          basedir: /Users/dowonlee/Desktop/Work/tmp/config-repo
#          username: [username]
#          password: [password]
        native:
          search-locations: C:\WSJ_EX\01.workspace\2022-11-17-spring-cloud-config-native-repository
#          uri: file://C:\WSJ_EX\01.workspace\2022-11-17-spring-cloud-config-native-repository 
# --------------------------------------------------------------------
     
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, beans, httptrace, busrefresh


