apiVersion: v1
kind: Service
metadata:
  name: my-configservice
spec:
  selector:
    app: my-configservice
  ports:
    - protocol: TCP
      port: 8888       # 클러스터 내에서 서비스가 사용할 포트
      targetPort: 88888  # 컨테이너의 포트
      nodePort: 8888   # 노드에서 사용할 포트
  type: NodePort
