#-------------------------------------
# type 1
#-------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: my-configservice
spec:
  selector:
    app: my-configservice
  ports:
    - protocol: TCP
      port: 8888 # sevice 가 클러스터 내에서 서비스가 사용하는 포트
      targetPort: 8888  # 컨테이너에서 사용할 포트
  type: LoadBalancer

##-------------------------------------
## type 2 nodeport
##-------------------------------------
#apiVersion: v1
#kind: Service
#metadata:
#  name: my-apigatewayservice
#spec:
#  selector:
#    app: my-apigatewayservice
#  ports:
#    - protocol: TCP
#      port: 8000       # 클러스터 내에서 서비스가 사용할 포트
#      targetPort: 8001  # 컨테이너의 포트
#      nodePort: 8000   # 노드에서 사용할 포트
#  type: NodePort
#
